In [2]:
#basic math and statistics

import numpy as np
from numpy.random import randn

In [4]:
np.set_printoptions(precision=2)

In [5]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
np.random.seed(11)
c = np.random.randn(6)
c

array([ 1.75, -0.29, -0.48, -2.65, -0.01, -0.32])

In [10]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [11]:
c+a

array([ 2.75,  1.71,  2.52,  1.35,  4.99,  5.68])

In [12]:
c-a

array([ 0.75, -2.29, -3.48, -6.65, -5.01, -6.32])

In [13]:
c*a

array([  1.75,  -0.57,  -1.45, -10.61,  -0.04,  -1.92])

In [14]:
c/a

array([  1.75e+00,  -1.43e-01,  -1.62e-01,  -6.63e-01,  -1.66e-03,
        -5.33e-02])

In [16]:
aa = np.array([[2.,4.,6.],[1.,3.,5.], [10.,20.,30.]])
aa

array([[  2.,   4.,   6.],
       [  1.,   3.,   5.],
       [ 10.,  20.,  30.]])

In [17]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
bb

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [18]:
aa*bb #matrix multiplication

array([[   0.,    4.,   12.],
       [   3.,   12.,   25.],
       [  60.,  140.,  240.]])

In [19]:
np.dot(aa,bb) #matrix dot product

array([[  48.,   60.,   72.],
       [  39.,   48.,   57.],
       [ 240.,  300.,  360.]])

In [21]:
import pandas as pd
from pandas import Series, DataFrame

import scipy
from scipy import stats

In [22]:
diabetes = pd.read_csv("diabetes.csv")
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Class  
0                     0.627   50      1  
1                     0.351   31      0  
2                     0.672   32      1  
3                     0.167   21      0  
4                     2.288   33      1

In [23]:
diabetes.shape

(768, 9)

In [24]:
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Class                         int64
dtype: object

In [25]:
diabetes.describeribe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age       Class  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [27]:
diabetes.groupby("Class").size()

Class
0    500
1    268
dtype: int64

In [28]:
diabetes.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Class                        0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Class                     0.130548  0.292695                  0.173844   

                               Age     Class  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Class                     0.238356  1.000000

Per the class, some ML algorithms like linear regerssion and logit suffer poor performance if there are highly correlated attributes in the data set.  

You can specify the correlation method by using method call in corr() (e.g. method="pearson", which is the default)